require 'nokogiri'
require 'open-uri'
require 'pry'
require 'colorize'

require_relative '../lib/cheers/beer'
require_relative '../lib/cheers/brewery'
require_relative '../lib/cheers/cli'
require_relative '../lib/cheers/scraper'
require_relative '../lib/cheers/version'